
thread '<unnamed>' panicked at lib/src/metta/types.rs:145:22:
Incorrect function type: (->)(A)
stack backtrace:
   0:     0x7fb0db9ee770 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h6d42cc84fc840290
   1:     0x7fb0dba3ee23 - core::fmt::write::h5af61a909e3ec64d
   2:     0x7fb0db9e2d73 - <unknown>
   3:     0x7fb0db9ee5c2 - <unknown>
   4:     0x7fb0db9f0b8f - <unknown>
   5:     0x7fb0db9f09fa - std::panicking::default_hook::h52e9e7314e0255f6
   6:     0x7fb0db9f15a2 - std::panicking::rust_panic_with_hook::h541791bcc774ef34
   7:     0x7fb0db9f134a - <unknown>
   8:     0x7fb0db9eec89 - std::sys::backtrace::__rust_end_short_backtrace::ha04e7c0fc61ded91
   9:     0x7fb0db9f0fdd - rust_begin_unwind
  10:     0x7fb0db5ea850 - core::panicking::panic_fmt::h5764ee7030b7a73d
  11:     0x7fb0db6c2b5e - <unknown>
  12:     0x7fb0db6c1458 - hyperon::metta::types::get_atom_types_v2::h52e5391a02efd6a1
  13:     0x7fb0db6b8064 - <unknown>
  14:     0x7fb0db6c0bc0 - hyperon::metta::types::get_atom_types_v2::h52e5391a02efd6a1
  15:     0x7fb0db6b8064 - <unknown>
  16:     0x7fb0db6c0bc0 - hyperon::metta::types::get_atom_types_v2::h52e5391a02efd6a1
  17:     0x7fb0db6c06c3 - hyperon::metta::types::get_atom_types::hec122c1a99d99dd8
  18:     0x7fb0db67edd9 - <unknown>
  19:     0x7fb0db654e5c - <unknown>
  20:     0x7fb0db6782e9 - <unknown>
  21:     0x7fb0db671d38 - hyperon::metta::interpreter::call_native_symbol::h16719fe55d5526e5
  22:     0x7fb0db65ef57 - <unknown>
  23:     0x7fb0db719186 - hyperon::metta::runner::RunContext::step::h1facd7b54bd96d9d
  24:     0x7fb0db714aee - hyperon::metta::runner::RunnerState::run_step::ha0b20a7e70085207
  25:     0x7fb0db714919 - hyperon::metta::runner::RunnerState::run_to_completion::he7c4f68648cfc995
  26:     0x7fb0db6292de - metta_run
  27:     0x7fb0db60dbb3 - <unknown>
  28:     0x7fb0db5f4c0f - <unknown>
  29:           0x547ac6 - <unknown>
  30:           0x517eb3 - _PyObject_MakeTpCall
  31:           0x52b940 - _PyEval_EvalFrameDefault
  32:           0x52360b - PyEval_EvalCode
  33:           0x647497 - <unknown>
  34:           0x644d4f - <unknown>
  35:           0x651010 - <unknown>
  36:           0x650d5b - _PyRun_SimpleFileObject
  37:           0x650b84 - _PyRun_AnyFileObject
  38:           0x64f90f - Py_RunMain
  39:           0x6275c7 - Py_BytesMain
  40:     0x7fb0dc47e24a - <unknown>
  41:     0x7fb0dc47e305 - __libc_start_main
  42:           0x627461 - _start
  43:                0x0 - <unknown>

thread '<unnamed>' panicked at library/core/src/panicking.rs:218:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x7fb0db9ee770 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h6d42cc84fc840290
   1:     0x7fb0dba3ee23 - core::fmt::write::h5af61a909e3ec64d
   2:     0x7fb0db9e2d73 - <unknown>
   3:     0x7fb0db9ee5c2 - <unknown>
   4:     0x7fb0db9f0b8f - <unknown>
   5:     0x7fb0db9f09fa - std::panicking::default_hook::h52e9e7314e0255f6
   6:     0x7fb0db9f15a2 - std::panicking::rust_panic_with_hook::h541791bcc774ef34
   7:     0x7fb0db9f1316 - <unknown>
   8:     0x7fb0db9eec89 - std::sys::backtrace::__rust_end_short_backtrace::ha04e7c0fc61ded91
   9:     0x7fb0db9f0fdd - rust_begin_unwind
  10:     0x7fb0db5ea88d - core::panicking::panic_nounwind_fmt::h6a24774852878975
  11:     0x7fb0db5ea922 - core::panicking::panic_nounwind::hbbbf5b15de703440
  12:     0x7fb0db5eab1e - core::panicking::panic_cannot_unwind::h8c0d27499c4c90fa
  13:     0x7fb0db62963b - metta_run
  14:     0x7fb0db60dbb3 - <unknown>
  15:     0x7fb0db5f4c0f - <unknown>
  16:           0x547ac6 - <unknown>
  17:           0x517eb3 - _PyObject_MakeTpCall
  18:           0x52b940 - _PyEval_EvalFrameDefault
  19:           0x52360b - PyEval_EvalCode
  20:           0x647497 - <unknown>
  21:           0x644d4f - <unknown>
  22:           0x651010 - <unknown>
  23:           0x650d5b - _PyRun_SimpleFileObject
  24:           0x650b84 - _PyRun_AnyFileObject
  25:           0x64f90f - Py_RunMain
  26:           0x6275c7 - Py_BytesMain
  27:     0x7fb0dc47e24a - <unknown>
  28:     0x7fb0dc47e305 - __libc_start_main
  29:           0x627461 - _start
  30:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
Command terminated by signal 6
0.05user 0.00system 0:00.38elapsed 16%CPU (0avgtext+0avgdata 28828maxresident)k
0inputs+0outputs (0major+3283minor)pagefaults 0swaps
INFO
