[(Error (py-atom langchain_openai.ChatOpenAI) Exception caught:
RuntimeError: Failed to find "langchain_openai.ChatOpenAI"

At:
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/stdlib.py(137): find_py_obj
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/stdlib.py(146): get_py_atom
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/atoms.py(469): execute
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/atoms.py(234): _priv_call_execute_on_grounded_atom
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/runner.py(209): run
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/metta.py(35): main
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/bin/metta(8): <module>
)]
