Traceback (most recent call last):
  File "/mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/bin/metta", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/metta.py", line 35, in main
    for result in metta.run(program):
  File "/mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/runner.py", line 210, in run
    self._run_check_for_error()
  File "/mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/runner.py", line 224, in _run_check_for_error
    raise RuntimeError(err_str)
RuntimeError: byte range = (79..109) | Could not parse integer: '555565404224292694404015791808', number too large to fit in target type
